core/core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

from directory import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("directory/", include("directory.urls", namespace="directory"), name="directory"),
]

if settings.DEBUG:
    # Django debug toolbar
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    # Static files (images, css, javascript, etc.)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/directory/urls.py
"""
urls for :mod:`directory` application.

:creationdate:  12/02/2023 19:42
:moduleauthor: François GUÉRIN <fguerin@ville-tourcoing.fr>
:modulename: directory.urls
"""
from django.urls import path
from directory import views

__author__ = "fguerin"

app_name = "directory"

urlpatterns = [
    path("", views.StudentListView.as_view(), name="student_list"),
    path("add/", views.StudentCreateView.as_view(), name="student_add"),
    path("<int:pk>", views.StudentDetailView.as_view(), name="student_detail"),
    path("<int:pk>/update/", views.StudentUpdateView.as_view(), name="student_update"),
]

core/directory/models/helpers.py
"""Helpers for models on :mod:`directory`."""

import logging

from django.apps import apps
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.db import models
from django_currentuser.middleware import get_current_authenticated_user

logger = logging.getLogger(__name__)


class Administrable(models.Model):
    """An administrable model takes cares of when and who created and updated it."""

    #: Creation date as a :class:`python:datetime.datetime`
    created_at = models.DateTimeField(
        verbose_name=_("created at"),
        auto_now_add=True,
        editable=False,
    )

    #: Creator as a :class:`django:django.contrib.auth.models.User`
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("created by"),
        related_name="%(app_label)s_%(class)s_owned",  # noqa
        default=1,
        on_delete=models.SET_DEFAULT,
        editable=False,
    )

    #: Update date as a :class:`python:datetime.datetime`
    updated_at = models.DateTimeField(
        verbose_name=_("created at"),
        auto_now=True,
        editable=False,
        null=True,
    )

    #: Updater as a :class:`django:django.contrib.auth.models.User`
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("created by"),
        related_name="%(app_label)s_%(class)s_updated",  # noqa
        null=True,
        on_delete=models.SET_NULL,
        editable=False,
    )

    class Meta:
        """Meta class."""

        abstract = True

    def save_base(
        self,
        raw=False,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
    ):
        """
        Get the creator and  updater from the current thread and save it.

        .. note::
           Into the into:

           + :attr:`eventrequest.models.helpers.Administrable.created_by`
           + :attr:`eventrequest.models.helpers.Administrable.updated_by`

        :param raw: Raw SQL query ?
        :param force_insert: Force insertion
        :param force_update: Force update
        :param using:  DB alias used
        :param update_fields: List fields to update
        :return: Nothing
        """
        current_user = get_current_authenticated_user()
        default_user = apps.get_model(settings.AUTH_USER_MODEL).objects.get(pk=1)

        if current_user is None:
            current_user = default_user
            logger.warning(
                f"{self.__class__.__name__}::save_base() "
                f'Unable to get the current user from local thread: setting the default one: "{current_user}"'
            )

        # Looks like an instance creation
        if self.updated_by is None and self.created_by == default_user:
            self.created_by = self.updated_by = current_user
            logging.info(
                f"{self.__class__.__name__}::save_base() "
                f"Creates a new instance ({self}): created_by = {self.created_by}"
            )
        else:
            self.updated_by = current_user
            logging.info(
                f"{self.__class__.__name__}::save_base() "
                f"Updates an existing instance ({self}): updated_by = {self.updated_by}"
            )

        super(Administrable, self).save_base(
            raw=raw,
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )

core/directory/forms.py
"""
forms for :mod:`directory` application.

:creationdate:  12/02/2023 20:04
:moduleauthor: François GUÉRIN <fguerin@ville-tourcoing.fr>
:modulename: directory.forms
"""
import logging
from django import forms
from django.utils.translation import gettext as _
from directory import models

__author__ = "fguerin"
logger = logging.getLogger(__name__)


class SearchForm(forms.Form):
    """Simple form for students search."""

    name = forms.CharField(
        max_length=255,
        label=_("Name"),
        required=False,
    )


class StudentCreateForm(forms.ModelForm):
    """For to create a new Student instance."""

    class Meta:
        """Metaclass for :class:`directory.forms.StudentCreateForm`."""

        model = models.Student
        exclude = []


class StudentUpdateForm(forms.ModelForm):
    """For to create a new Student instance."""

    class Meta:
        """Metaclass for :class:`directory.forms.StudentUpdateForm`."""

        model = models.Student
        exclude = []

core/directory/views.py
"""Views for the :mod:`directory` application."""
import logging

from django.utils.translation import gettext as _
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from directory import models, forms

logger = logging.getLogger(__name__)


class StudentDetailView(DetailView):
    """Detail of a :class:`` instance."""

    model = models.Student

    def get_context_data_data(self, **kwargs):
        """Get context_data for template;"""
        context_data = super().get_context_data_data(**kwargs)
        context_data["page_title"] = _("Students")
        logger.debug(
            "%s::get_context_data_data() context_data = %s",
            self.__class__.__name__,
            context_data,
        )
        return context_data


class StudentListView(ListView):
    """List of a :class:`` instances."""

    model = models.Student

    def get_context_data_data(self, **kwargs):
        """Get context_data for template;"""
        context_data = super().get_context_data_data(**kwargs)
        context_data["page_title"] = "Students"
        logger.debug(
            "%s::get_context_data_data() context_data = %s",
            self.__class__.__name__,
            context_data,
        )
        return context_data


class StudentCreateView(CreateView):
    """View to create a :class:`directory.models.Student` instance."""

    model = models.Student
    form_class = forms.StudentCreateForm

    def get_context_data_data(self, **kwargs):
        """Get context_data for template;"""
        context_data = super().get_context_data_data(**kwargs)
        context_data["page_title"] = _("Create a new student")
        logger.debug(
            "%s::get_context_data_data() context_data = %s",
            self.__class__.__name__,
            context_data,
        )
        return context_data


class StudentUpdateView(UpdateView):
    """View to update a :class:`directory.models.Student` instance."""

    model = models.Student
    form_class = forms.StudentUpdateForm

    def get_context_data_data(self, **kwargs):
        """Get context_data for template;"""
        context_data = super().get_context_data_data(**kwargs)
        context_data["page_title"] = _("Create a student: {student}").format(student=self.object)
        logger.debug(
            "%s::get_context_data_data() context_data = %s",
            self.__class__.__name__,
            context_data,
        )
        return context_data

core/directory/templates/base_layout.html
{% extends "base.html" %}
{% load static %}
{% block extrahead %}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
{% endblock extrahead %}

core/directory/templates/directory/hello.html
{% extends "base_layout.html" %}

{% block main-content %}<p>Hello, {{ name }} !</p>{% endblock main-content %}

core/directory/templates/directory/student_detail.html
{% extends "base_layout.html" %}

{% block main-content %}
{% endblock main-content %}

core/directory/templates/directory/student_list.html
{% extends "base_layout.html" %}
{% load i18n %}

{% block main-content-heading %}<!-- Add search here... -->
{% endblock main-content-heading %}

{% block main-content %}
  <h1>{{ page_title }}</h1>
  {% for student in student_list %}
    <table class="table table-responsive">
      <thead>
      <tr>
        <th>#</th>
        <th>{% translate "Last name" %}</th>
        <th>{% translate "First name" %}</th>
        <th>{% translate "Contact" %}</th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
      {% for student in student_list %}
        <tr>
          <td>{{ student.pk }}</td>
          <td>{{ student.last_name }}</td>
          <td>{{ student.first_name }}</td>
          <td>
            <address>
              {% if student.phone_number %}
                <span class="text-nowrap">{% translate "PN:" %}{{ student.phone_number }}</span>
              {% endif %}
              {% if student.email %}
                <span class="text-nowrap">{% translate "Email:" %}{{ student.email|urlize }}</span>
              {% endif %}
            </address>
          </td>
          <td>
            <a href="{% url "directory:student_detail" pk=student.pk %}">{% translate "Detail" %}</a>
            <a href="{% url "directory:student_update" pk=student.pk %}">{% translate "Update" %}</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% endfor %}
{% endblock main-content %}

{% block main-content-footer %}
  <div style="margin-left: auto; margin-right: auto;">
    <a href="{% url "directory:student_add" %}">{% translate "Add a student" %}</a>
  </div>
{% endblock main-content-footer %}

core/templates/base.html
{% load static %}<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport"
        content="width=device-width, initial-scale=1">

  <title>{{ page_title }}</title>
  <meta name="description"
        content="{{ page_description }}">
  <meta name="author"
        content="François GUÉRIN <frague59@gmail.com>">

  <meta property="og:title"
        content="{{ page_title }}">
  <meta property="og:type"
        content="website">
  <meta property="og:url"
        content="https://www.sitepoint.com/a-basic-html5-template/">
  <meta property="og:description"
        content="{{ page_description }}">

  <link rel="icon"
        href="{% static "images/favicon.ico" %}"
        type="image/x-icon">
  {#  <link rel="icon" href="{% static "images/favicon.svg" %}" type="image/svg+xml">#}
  {#  <link rel="apple-touch-icon" href="{% static "images/apple-touch-icon.png" %}">#}
  {% block extrahead %}
    <link rel="stylesheet"
          href="{% static "css/styles.css" %}">
  {% endblock extrahead %}
</head>

<body>
<header>
  {% block header %}
    <header>{% block header-content %}{% endblock header-content %}</header>
  {% endblock header %}
  {% block main %}
    <main>{% block main-content %}{% endblock main-content %}</main>
  {% endblock main %}
  {% block footer %}
    <footer>{% block footer-content %}{% endblock footer-content %}</footer>
  {% endblock footer %}
  {% block extrajs %}
    <script src="{% static "js/index.js" %}"></script>
  {% endblock extrajs %}
</header>
<main class="main">
  {% block title %}
    <h1>{{ title }}</h1>
  {% endblock title %}
  {% block main-content-heading %}<!-- main-content-heading -->{% endblock main-content-heading %}
  {% block main-content %}<!-- main-content -->{% endblock main-content %}
  {% block main-content-footer %}<!-- main-content-footer -->{% endblock main-content-footer %}
</main>
<footer></footer>
</body>
</html>